### ISSUE TITLE
Convenient if Utils.getMostRecentReport would accept an array of form names

### ISSUE THREAD

**Issue by pkitutu** [medic/cht-nootils#22]
This is related to #16 .
This will help to avoid having to call this function twice in some situations. An example below illustrates this:

I need to get the latest edd that can either exist in a pregnancy report or an anc report:
This implies that one may write this piece of code:
```
const latestPregnancyReport = Utils.getMostRecentReport('pregnancy')
const latestANCReport = Utils.getMostRecentReport('anc_visit')
if (Utils.isFirstReportNewer(latestANCReport, latestPregnancyReport)) {
  return Utils.getField(latestANCReport, 'edd')
}
return Utils.getField(latestPregnancyReport, 'edd')
```
rather than this:
```
const latestReport = Utils.getMostRecentReport(['pregnancy', 'anc_visit'])
Utils.getField(latestReport, 'edd')
```

**Comment by craig-landry** [comment]
This will be included in the next CHT release, with this dependency being handled along with other dep upgrades. The current ticket for that is https://github.com/medic/cht-core/issues/7349

**Comment by derickl** [comment]
How far out is the next CHT release? Would it make sense to work on the 3 remaining open issues so that they make it for the release?

**Comment by craig-landry** [comment]
> How far out is the next CHT release? Would it make sense to work on the 3 remaining open issues so that they make it for the release?

I'd say "not far". If you mean to suggest that you and/or @pkitutu want to submit a couple more PRs, then yes, sooner than later is best. @jkuester is going through dependency updates to bring in the latest from this repo.... in fact he's already done that for this repo, but it won't hurt to bump the version again if needed. Ideally we just do it before someone goes and does manual release testing, but there's still time before then.
